### ISSUE TITLE
Time Selected is "NONE" on order and email

### ISSUE THREAD

**Issue by gbettant** [WC-Local-Pickup/woocommerce-local-pickup-time#124]
**Describe the bug**
Since today, the orders i receive have a time selected as "none".
This is new, everything was correct before.
The customers have selected the time but on the order and email sent, pickup time selected is "none"

**To Reproduce**
1. Go to https://www.maisonbettant.fr/eshop
2. Make an order
3. Select time slot
4. Received email indicates "none"

**Expected behavior**
Correct selected time on the order

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce and this plugin are active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- Website URL: https://www.maisonbettant.fr/eshop
- PHP Version: 7.4.15
- WordPress Version: 5.7
- WooCommerce Version: 5.1
- Plugin Version: 1.3.13 
- WordPress Timezone Setting: Paris
- WordPress Date Format Setting: j F Y
- WordPress Time Format Setting: G \h i \m\i\n
- All Plugin Start/End Pickup Time Settings: 8AM / 7PM
- Plugin Pickup Time Interval Setting: 30 minutes
- Plugin Pickup Time Delay Setting: 4 hours
- Plugin Orders Per Interval: not specified
- Plugin Pickup Time Open Days Ahead Setting: 30

**Comment by jquiros2** [comment]
Am having the same issue on some orders, and have not found the reason despite debugging.
So orders this is happening on we are contacting the person who placed the order requesting the time/date for delivery or pickup.

**Comment by gbettant** [comment]
I reinstalled the 1.3.12 version instead of the 1.3.13 : it now works properly, and don't have "none" anymore ....

**Comment by gbettant** [comment]
So this means the problem is in the 1.3.13 version

**Comment by timnolte** [comment]
@gbettant OK, thanks for that information. I'll take a look at what code changes were made between the 2 releases and see what is going on.

**Comment by gbettant** [comment]
Ok great, hope installing the future 1.3.14 will get rid of this "none"

**Comment by jquiros2** [comment]
> @gbettant OK, thanks for that information. I'll take a look at what code changes were made between the 2 releases and see what is going on.

@timnolte Thanks so much!  I also reinstalled 1.3.12 and will report if it "sometimes" (in my case) happens again as that might help see if it's an issue with my environment or not.

**Comment by gbettant** [comment]
it was also sometime for me with 1.3.13, id say about 3 or 4 times out of 5 i had "none". Now with 1.3.12 all seems fine.

**Comment by mike-battistella** [comment]
In my installation it also occurs that sometimes the time field is "None" - I've experienced this after upgrading from WooCommerce 4 to 5 — but not sure if I've also upgraded this plugin at the same time.

**Comment by OHOHere** [comment]
I'm having the same issue. No PickUp Time Selected information is saved.  But I have noticed that if it is the customers first order that the selected Pick Up Time is not saved so it does not get to the email nor the order information.  But the second time the customer orders, or if still logged in from the first order, the selected Pick Up Time is shown and saved correctly.

**Comment by MaW-cmkbk** [comment]
Same issue. From 12 orders there was 5 with None in pickup-time.

**Comment by timnolte** [comment]
With the latest release I'm pretty sure that this issue should be resolved.

**Comment by jquiros2** [comment]
Am adding this in case it helps track it down as I just spent most of the day trying and am just not good enough!

I decided to update because I started having issues with 1.3.12 (thinking all the updates in Wordpress, woocommerce, etc could be causing it).

I updated to the latest - 1.4.2 and I am having this issue again.

I'm tracking the variable/field/order meta and logging with the following:

  $order = wc_get_order($order_id);
  $pickup_timeTMP = $order->get_meta( '_local_pickup_time_select', true);
  $jq_fp = fopen("/var/www/html/berzerker/wp-content/themes/divi-child/myqvars.log","a");
  $jq_date = date("Y-m-d_H:i:s");
  fwrite($jq_fp, $jq_date.$order_id."-A_order is ".$order."\n");
  fwrite($jq_fp, $jq_date.$order_id."-A_order_id is ".$order_id."\n");
  fwrite($jq_fp, $jq_date.$order_id."-A_pickup_timeTMP is ".$pickup_timeTMP."\n");
  fclose($jq_fp);


For some reason, when I enter an order as a shop owner or admin, the _local_pickup_time_select IS set, but when adding as a customer it IS NOT set.

So- might it have something to do with "protected" in the code?

Thanks again for any pointers!

**Comment by jquiros2** [comment]
Ouch! reverting to 1.3.12 does not fix it anymore, probably due to all the other woo/wp updates.
@MaW-cmkbk , @OHOHere , @mike-battistella , @gbettant how are you guys doing with this?

**Comment by rolodoom** [comment]
I'm getting still this error, so I think this thread should be opened again. There is also no pickup date on the order not on the email

- Plugin Version: 1.4.2
- PHP Version: 7.4.33 
- WordPress Version: 6.3
- WooCommerce Version: 8.0.2

I opened a detail bug explanation on #225
